The first lab

In [0]:
import numpy as np

In [6]:
# (4*2) array

a = np.array([[ 0, 1], [ 3, 4],[ 5, 6], [ 7, 8]])
print(a)

[[0 1]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
# asserding, deserding 

b = np.array([ 3, 6, 7, 8, 10, 1, 9, 2, 5, 4])
c = np.sort(b)
print(c)
print(c[:: -1] )


[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [15]:
# the reshape
d = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(np.reshape(d, (3,-1))) # -1 acts like 2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
v = np.vstack(b)
print(v)

[[ 3]
 [ 6]
 [ 7]
 [ 8]
 [10]
 [ 1]
 [ 9]
 [ 2]
 [ 5]
 [ 4]]


In [28]:
h = np.hstack(v)
print(h)

[ 3  6  7  8 10  1  9  2  5  4]


In [30]:
r1 = np.random.randint(10, size=5)
r2 = np.random.randint(10, size=5)
print(r1)
print(r2)
print(np.intersect1d(r1,r2))

[8 5 1 8 6]
[0 4 4 2 3]
[]


In [37]:
r3 = np.random.randint(0,10 , size = (5,5))
print(r3)
s = np.sort(r3, axis=1)
print (s)
print (s[:, 4]) # max
print(s[:, 0])

[[9 7 4 2 9]
 [5 5 2 9 4]
 [5 0 2 2 5]
 [0 8 4 1 1]
 [5 1 4 9 9]]
[[2 4 7 9 9]
 [2 4 5 5 9]
 [0 2 2 5 5]
 [0 1 1 4 8]
 [1 4 5 9 9]]
[9 9 5 8 9]
[2 2 0 0 1]


In [42]:
from numpy import mean, absolute

r4 = np.random.randint(0, 200 , size = 100)
print (r4)

print (mean(r4))

from astropy.stats import median_absolute_deviation

print(median_absolute_deviation(r4))

print(np.std(r4))

[ 91  71  10 185   3  44  91  10  68 199  84 158  77  74  54 118 194 141
  60 154  39  49 103 169 155 157 181 136 166  70  23  48 155 146   5  89
 190  45  50 109  76  80  93  22  79 168 180 191  73  79 128  25 116 168
  19 183  20   7 109  42 176 139 198 154 117  35 129 167  26  28 157 177
   4  46 118 186 122  40 113 178 170  32 142 120 117  48 150   2  85  79
  39  68  29 136  23  82 136 163 107 115]
99.82
53.5
58.17806803254985


In [43]:
x = np.random.random((5, 5))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.61022533 0.61832369 0.79340001 0.82351229 0.53319262]
 [0.78622262 0.47834411 0.99564201 0.95895162 0.69515644]
 [0.27187614 0.69014988 0.4736721  0.38937925 0.5526775 ]
 [0.77440839 0.09830173 0.38523592 0.4531823  0.64718186]
 [0.55827887 0.93130089 0.18924225 0.48413359 0.38655171]]
[[0.57048993 0.57951479 0.77462061 0.80817787 0.48464434]
 [0.76662211 0.42352092 1.         0.95911206 0.66513755]
 [0.19343209 0.65955821 0.41831441 0.32437808 0.50635838]
 [0.75345627 0.         0.31976073 0.39548049 0.61167446]
 [0.51260057 0.92829798 0.10134452 0.42997274 0.32122706]]


In [45]:
mm = np.random.randint(0,10 , size = (4,4,3))
nn = np.random.randint(0,10 , size = (4,4))
print(mm)
print(nn)

# print(np.einsum('ijk,ij',mm,nn))
mm * nn[:,:,None]

[[[2 0 0]
  [6 3 4]
  [7 3 2]
  [2 0 0]]

 [[0 4 0]
  [8 4 7]
  [1 9 4]
  [7 1 0]]

 [[9 7 2]
  [9 8 4]
  [1 0 3]
  [0 0 7]]

 [[5 5 9]
  [1 1 1]
  [2 7 6]
  [7 1 5]]]
[[6 1 6 3]
 [9 3 7 6]
 [4 9 9 0]
 [8 7 3 9]]


array([[[12,  0,  0],
        [ 6,  3,  4],
        [42, 18, 12],
        [ 6,  0,  0]],

       [[ 0, 36,  0],
        [24, 12, 21],
        [ 7, 63, 28],
        [42,  6,  0]],

       [[36, 28,  8],
        [81, 72, 36],
        [ 9,  0, 27],
        [ 0,  0,  0]],

       [[40, 40, 72],
        [ 7,  7,  7],
        [ 6, 21, 18],
        [63,  9, 45]]])