# **Lab 5**



Instructions in Readme


 Calculate the performance (e.g., MSE) of the algorithm on the validation dataset

 Once you're happy, make predictions for the test dataset
 (If you have time) Use pandas to find the best- and the worst-rated jokes

 Make sure you save your changes in Github!

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [57]:
df = pd.read_csv('https://raw.githubusercontent.com/ParastooAzizinezhad/CE888-Labs/master/Lab5/jester-data-1.csv', header=None)
print(df)

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


In [58]:
x = np.array([[1, 2, 3], [1, 5, 6]], np.int32)
x

array([[1, 2, 3],
       [1, 5, 6]], dtype=int32)

In [59]:

np.where(x!=1)

(array([0, 0, 1, 1]), array([1, 2, 1, 2]))

In [60]:
arr = df.values
print(arr.shape)

(24983, 101)


In [61]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1835357 (1835357,)


In [0]:
def replace(orig, percentage=0.1): # 10% = 0.1
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [63]:
new_arr, idx = replace(arr, 0.1)

new_arr

array([[ 74.  ,  -7.82,   8.79, ...,  99.  ,  99.  ,  99.  ],
       [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
       [ 49.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       ...,
       [ 39.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 72.  ,   2.43,   2.67, ...,  99.  ,  99.  ,  99.  ]])

In [64]:
idx

(array([ 5157, 13552,  2763, ...,  4750,   164,  6048]),
 array([69, 70, 32, ..., 31, 56, 45]))

In [65]:
arr[idx[0][0], idx[1][0]]

6.31

In [66]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [67]:
arr

array([[ 74.  ,  -7.82,   8.79, ...,  99.  ,  99.  ,  99.  ],
       [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
       [ 49.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       ...,
       [ 39.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 72.  ,   2.43,   2.67, ...,  99.  ,  99.  ,  99.  ]])

In [68]:
new_arr

array([[ 74.  ,  -7.82,   8.79, ...,  99.  ,  99.  ,  99.  ],
       [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
       [ 49.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       ...,
       [ 39.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 72.  ,   2.43,   2.67, ...,  99.  ,  99.  ,  99.  ]])

first test

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)


In [0]:
#df.replace(99, np.nan)

In [0]:
n_latent_factors = 4

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [111]:
latent_user_preferences.shape, latent_item_features.shape

((24983, 4), (101, 4))

In [0]:
#latent_item_features
#latent_user_preferences

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=5):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating !=99:
                    err = train(user_id, item_id, rating)
                    #val_err = calculate_val_err(user_id, item_id, rating) 
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
          
            print(mse)

In [114]:
sgd()

48.7056277011759
30.77417694639405
26.533585243386725
25.16945219644713
24.764322655968694


In [116]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 7.265e+01,  7.770e-01,  4.025e-01, ...,  8.409e-01, -2.767e-01,
         1.235e+00],
       [ 9.644e+01,  1.170e+00,  2.024e-01, ...,  9.325e-01,  8.422e-02,
         1.628e+00],
       [ 5.709e+01,  4.649e-01,  3.037e-01, ...,  7.380e-01, -1.325e-01,
         7.943e-01],
       ...,
       [ 3.967e+01,  4.779e-01, -1.042e-01, ...,  3.542e-01,  7.108e-02,
         7.362e-01],
       [ 3.829e+01,  5.284e-01,  4.131e-01, ...,  3.786e-01,  4.733e-02,
         5.260e-01],
       [ 7.442e+01,  1.025e+00,  5.333e-01, ...,  6.990e-01,  7.779e-02,
         1.165e+00]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

In [118]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0    ...                         100
0         (74.0, 72.6526450086764)  ...  (99.0, 1.2354864575854425)
1       (100.0, 96.43782647598296)  ...  (1.07, 1.6280061270113229)
2       (49.0, 57.086280023408136)  ...  (99.0, 0.7943391972879383)
3        (48.0, 51.45960181591448)  ...  (99.0, 0.6894968522067422)
4        (99.0, 44.81012127192661)  ...   (1.6, 0.7940734005782435)
...                            ...  ...                         ...
24978  (100.0, 101.26881931707176)  ...  (7.43, 1.6759842231401494)
24979    (91.0, 82.96536199552334)  ...  (8.45, 1.3529357302991123)
24980    (39.0, 39.66700239123086)  ...    (99.0, 0.73624721812749)
24981    (37.0, 38.28803660350957)  ...  (99.0, 0.5259501540748829)
24982     (72.0, 74.4222883688703)  ...  (99.0, 1.1653006727643005)

[24983 rows x 101 columns]

Second test

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)


In [0]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=10):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating !=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 20) == 0:
            print(mse)

In [126]:
sgd()

59.90005475032248


In [127]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

array([[ 7.491e+01,  8.331e-01,  2.327e-01, ...,  7.777e-01,  1.902e-02,
         1.171e+00],
       [ 9.642e+01,  1.281e+00,  6.478e-01, ...,  1.008e+00,  2.893e-01,
         1.572e+00],
       [ 5.376e+01,  6.536e-01,  2.602e-01, ...,  5.600e-01,  8.451e-02,
         8.574e-01],
       ...,
       [ 3.811e+01,  5.529e-01,  3.341e-01, ...,  4.001e-01,  1.737e-01,
         6.360e-01],
       [ 3.759e+01,  3.045e-01, -7.311e-02, ...,  3.864e-01, -1.348e-01,
         5.517e-01],
       [ 7.435e+01,  7.099e-01,  3.528e-02, ...,  7.679e-01, -1.299e-01,
         1.125e+00]])

In [128]:
comparison_data

0    ...                         100
0         (74.0, 72.6526450086764)  ...  (99.0, 1.2354864575854425)
1       (100.0, 96.43782647598296)  ...  (1.07, 1.6280061270113229)
2       (49.0, 57.086280023408136)  ...  (99.0, 0.7943391972879383)
3        (48.0, 51.45960181591448)  ...  (99.0, 0.6894968522067422)
4        (99.0, 44.81012127192661)  ...   (1.6, 0.7940734005782435)
...                            ...  ...                         ...
24978  (100.0, 101.26881931707176)  ...  (7.43, 1.6759842231401494)
24979    (91.0, 82.96536199552334)  ...  (8.45, 1.3529357302991123)
24980    (39.0, 39.66700239123086)  ...    (99.0, 0.73624721812749)
24981    (37.0, 38.28803660350957)  ...  (99.0, 0.5259501540748829)
24982     (72.0, 74.4222883688703)  ...  (99.0, 1.1653006727643005)

[24983 rows x 101 columns]

third test

In [0]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=100):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating !=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 5) == 0:
            print(mse)

In [131]:
sgd()

60.08635728872799
24.62655969255694
24.56653263269913
24.519051161444715
24.47105327124617
24.337667951518043
23.495769092914557
20.48567218799301
18.467871950847634
18.04592345306062
17.943704194905287
17.909353081157025
17.894315118939083
17.886095179844183
17.880747072127328
17.87684374404125
17.873806276999527
17.87136732040542
17.869382969773117
17.86776282432503


In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

In [133]:
comparison_data

0    ...                          100
0        (74.0, 77.98515051589726)  ...  (99.0, -3.4877388159754457)
1       (100.0, 94.75530614392774)  ...   (1.07, 3.6716687501301304)
2        (49.0, 48.43427865987285)  ...    (99.0, 8.680343383000034)
3        (48.0, 47.95134305015556)  ...   (99.0, 2.6350996973317686)
4        (99.0, 99.57620035793445)  ...     (1.6, 3.996364311094376)
...                            ...  ...                          ...
24978  (100.0, 101.53707680351916)  ...   (7.43, 3.5378694627006326)
24979    (91.0, 84.38257092194691)  ...   (8.45, 2.3960298382514726)
24980    (39.0, 38.98648871718908)  ...  (99.0, -0.7755119145034868)
24981    (37.0, 38.14048262728361)  ...  (99.0, -0.4781198506479694)
24982    (72.0, 72.83316016416939)  ...    (99.0, 4.078931686771046)

[24983 rows x 101 columns]

In [136]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns
comparison_data

0    ...                          100
0        (74.0, 77.98515051589726)  ...  (99.0, -3.4877388159754457)
1       (100.0, 94.75530614392774)  ...   (1.07, 3.6716687501301304)
2        (49.0, 48.43427865987285)  ...    (99.0, 8.680343383000034)
3        (48.0, 47.95134305015556)  ...   (99.0, 2.6350996973317686)
4        (99.0, 99.57620035793445)  ...     (1.6, 3.996364311094376)
...                            ...  ...                          ...
24978  (100.0, 101.53707680351916)  ...   (7.43, 3.5378694627006326)
24979    (91.0, 84.38257092194691)  ...   (8.45, 2.3960298382514726)
24980    (39.0, 38.98648871718908)  ...  (99.0, -0.7755119145034868)
24981    (37.0, 38.14048262728361)  ...  (99.0, -0.4781198506479694)
24982    (72.0, 72.83316016416939)  ...    (99.0, 4.078931686771046)

[24983 rows x 101 columns]

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=5):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if rating !=99:
                    err = train(user_id, item_id, rating)
                    #val_err = calculate_val_err(user_id, item_id, rating) 
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
          
            print(mse)